# Use the official Python image as the base image
FROM nikolaik/python-nodejs:latest

# Install the application dependencies
# RUN npm install
# RUN pip install -r requirements.txt

# Define the entry point for the container
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]